# fly.toml app configuration file generated for random-crowdsourced on 2024-09-18T15:36:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'random-crowdsourced'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "5s"
  interval = "5m"
  method = "GET"
  timeout = "1s"
  path = "/"

[http_service.checks.headers]
  Fly-Health-Check = "true"

[[http_service.machine_checks]]
  image = "curlimages/curl"
  entrypoint = ["/bin/sh", "-c"]
  command = ["curl [$FLY_TEST_MACHINE_IP] | grep 'really really good random number generator'"]
  kill_signal = "SIGKILL"
  kill_timeout = "5s"

[deploy]
  strategy = "canary"

[[vm]]
  size = 'shared-cpu-1x'
